
min_viewport_width: 800
aspect_ratio: 4/3

threads: 16
frame_time: 100
camera_move_step: 0.5
camera_look_step_radians: 0.0872664626

width: 800
samples_per_pixel: 20
max_bounces: 20

preview_width: 128
preview_samples_per_pixel: 2
preview_max_bounces: 2